#lang ivy1.8

type node = { node0, node1, node2}

relation p(X:node)
relation q(X:node)
relation r(X:node)

# Does this p-node pair with q (true) or r (false)?
relation use_q(X:node)

# p <-> q pairing
function pq(X:node) : node
function qp(X:node) : node

# p <-> r pairing
function pr(X:node) : node
function rp(X:node) : node

after init {
    p(X) := false;
    q(X) := false;
    r(X) := false;
    }

action upq(x:node,y:node) = {
    require ~p(x) & ~q(y);
    p(x) := true;
    q(y) := true;
    use_q(x) := true;
    pq(x) := y;
    qp(y) := x;
}

action upr(x:node,y:node) = {
    require ~p(x) & ~r(y);
    p(x) := true;
    r(y) := true;
    use_q(x) := false;
    pr(x) := y;
    rp(y) := x;
}

# Remove one p and one q.
action downq(x:node,y:node) = {
    require p(x) & q(y);
    if use_q(x) {
        pq(qp(y)) := pq(x);
        qp(pq(x)) := qp(y);
        # use_q(qp(y)) stays true
    } else {
        pr(qp(y)) := pr(x);
        rp(pr(x)) := qp(y);
        use_q(qp(y)) := false;
    };
    p(x) := false;
    q(y) := false;
}

# Remove one p and one r.
action downr(x:node,y:node) = {
    require p(x) & r(y);
    if ~use_q(x) {
        pr(rp(y)) := pr(x);
        rp(pr(x)) := rp(y);
        # use_q(rp(y)) stays false
    } else {
        pq(rp(y)) := pq(x);
        qp(pq(x)) := rp(y);
        use_q(rp(y)) := true;
    };
    p(x) := false;
    r(y) := false;
}

# invariant p(X) -> exists Y. (q(Y) | r(Y))


# pq/qp invariants (same pattern)
invariant [invar_pq_1] forall NODE1,NODE0. qp(NODE0) ~= NODE1 | p(NODE1) | ~q(NODE0)
invariant [invar_pq_2] forall NODE1,NODE0. pq(NODE0) ~= NODE1 | q(NODE1) | ~p(NODE0) | ~use_q(NODE0)
invariant [invar_pq_3] forall NODE1,NODE0. pq(NODE1) = NODE0 | qp(NODE0) ~= NODE1 | ~q(NODE0)
invariant [invar_pq_4] forall NODE1,NODE0. pq(NODE0) ~= NODE1 | qp(NODE1) = NODE0 | ~p(NODE0) | ~use_q(NODE0)
invariant [invar_pq_5] forall NODE1,NODE0. qp(NODE0) ~= NODE1 | use_q(NODE1) | ~q(NODE0)

# pr/rp invariants (symmetric to pq/qp)
invariant [invar_pr_1] forall NODE1,NODE0. rp(NODE0) ~= NODE1 | p(NODE1) | ~r(NODE0)
invariant [invar_pr_2] forall NODE1,NODE0. pr(NODE0) ~= NODE1 | r(NODE1) | ~p(NODE0) | use_q(NODE0)
invariant [invar_pr_3] forall NODE1,NODE0. pr(NODE1) = NODE0 | rp(NODE0) ~= NODE1 | ~r(NODE0)
invariant [invar_pr_4] forall NODE1,NODE0. pr(NODE0) ~= NODE1 | rp(NODE1) = NODE0 | ~p(NODE0) | use_q(NODE0)
invariant [invar_pr_5] forall NODE1,NODE0. rp(NODE0) ~= NODE1 | ~use_q(NODE1) | ~r(NODE0)


export upq
export upr
export downq
export downr
