#lang ivy1.8

type node

relation p(X:node)
relation q(X:node)
relation r(X:node)

after init {
    p(X) := false;
    q(X) := false;
    r(X) := false;
}

action upq(x:node,y:node) = {
    require ~p(x) & ~q(y);
    p(x) := true;
    q(y) := true;
}

action upr(x:node,y:node) = {
    require ~p(x) & ~r(y);
    p(x) := true;
    r(y) := true;
}

action downq(x:node,y:node) = {
    require p(x) & q(y);
    p(x) := false;
    q(y) := false;
}

action downr(x:node,y:node) = {
    require p(x) & r(y);
    p(x) := false;
    r(y) := false;
}

#invariant p(X) -> exists Y. (q(Y) | r(Y))

export upq
export upr
export downq
export downr


invariant [invar_0] forall NODE2,NODE1,NODE0. ~r(NODE1) | ~q(NODE0) | p(NODE2) # qcost: 6
invariant [invar_1] forall NODE1,NODE0. ~r(NODE0) | ~q(NODE0) | ~r(NODE1) | NODE0 = NODE1 # qcost: 6
invariant [invar_2] forall NODE1,NODE0. p(NODE0) | ~q(NODE0) | p(NODE1) | NODE0 = NODE1 # qcost: 6
invariant [invar_3] forall NODE1,NODE0. ~r(NODE0) | p(NODE0) | p(NODE1) | NODE0 = NODE1 # qcost: 6
invariant [invar_4] forall NODE1,NODE0. ~r(NODE0) | p(NODE0) | ~r(NODE1) | NODE0 = NODE1 # qcost: 6
invariant [invar_5] forall NODE1,NODE0. ~q(NODE1) | p(NODE0) | ~q(NODE0) | NODE0 = NODE1 # qcost: 6
invariant [invar_6] forall NODE1,NODE0. ~q(NODE1) | ~q(NODE0) | ~r(NODE1) | NODE0 = NODE1 # qcost: 6
invariant [invar_7] forall NODE1,NODE0. q(NODE0) | r(NODE0) | q(NODE1) | ~p(NODE0) | r(NODE1) | NODE0 = NODE1 # qcost: 8
invariant [invar_8] forall NODE1,NODE0. ~p(NODE1) | r(NODE0) | q(NODE1) | ~p(NODE0) | r(NODE1) | NODE0 = NODE1 # qcost: 8
invariant [invar_9] forall NODE1,NODE0. ~p(NODE1) | q(NODE0) | r(NODE0) | q(NODE1) | ~p(NODE0) | NODE0 = NODE1 # qcost: 8
