#lang ivy1.8

type node = {node0, node1, node2, node3, node4}

relation p(X:node)
relation q(X:node)
relation r(X:node)

after init {
    p(X) := false;
    q(X) := false;
    r(X) := false;
}

action upq(x:node,y:node) = {
    require ~p(x) & ~q(y);
    p(x) := true;
    q(y) := true;
}

action upr(x:node,y:node) = {
    require ~p(x) & ~r(y);
    p(x) := true;
    r(y) := true;
}

action downq(x:node,y:node) = {
    require p(x) & q(y);
    p(x) := false;
    q(y) := false;
}

action downr(x:node,y:node) = {
    require p(x) & r(y);
    p(x) := false;
    r(y) := false;
}

#invariant p(X) -> exists Y. (q(Y) | r(Y))

export upq
export upr
export downq
export downr


invariant [invar_0] forall NODE1,NODE0,NODE4,NODE3,NODE2. p(NODE3) | p(NODE4) | ~r(NODE1) | ~q(NODE0) | ~r(NODE2) | ((NODE0 ~= NODE1 | NODE0 ~= NODE3 | NODE2 ~= NODE4 | NODE0 = NODE2) & (NODE0 ~= NODE1 | NODE2 ~= NODE4 | NODE0 = NODE3 | NODE0 = NODE2 | NODE2 = NODE3) & (NODE0 ~= NODE1 | NODE0 ~= NODE4 | NODE0 = NODE3 | NODE0 = NODE2 | NODE2 = NODE3) & (NODE0 ~= NODE3 | NODE2 ~= NODE4 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE1 ~= NODE3 | NODE2 ~= NODE4 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE0 ~= NODE2 | NODE1 = NODE3 | NODE0 = NODE1 | NODE1 = NODE4 | NODE0 = NODE3 | NODE3 = NODE4 | NODE0 = NODE4) & (NODE0 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE1 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 55
invariant [invar_1] forall NODE1,NODE0,NODE4,NODE3,NODE2. p(NODE3) | p(NODE4) | ~r(NODE1) | p(NODE2) | ~q(NODE0) | ((NODE0 ~= NODE3 | NODE1 ~= NODE4 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE0 ~= NODE1 | NODE0 ~= NODE4 | NODE0 = NODE3 | NODE0 = NODE2 | NODE2 = NODE3) & (NODE0 ~= NODE1 | NODE2 = NODE4 | NODE2 = NODE3 | NODE0 = NODE3 | NODE3 = NODE4 | NODE0 = NODE4 | NODE0 = NODE2) & (NODE0 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE1 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 41
invariant [invar_2] forall NODE1,NODE2,NODE3,NODE0. p(NODE3) | ~r(NODE0) | ~r(NODE1) | p(NODE2) | p(NODE1) | ((NODE0 ~= NODE3 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 19
invariant [invar_3] forall NODE1. ~r(NODE1) | p(NODE1) | (exists NODE0. (p(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_4] forall NODE1,NODE0,NODE4,NODE3,NODE2. ~q(NODE1) | p(NODE4) | ~r(NODE3) | ~q(NODE0) | ~r(NODE2) | ((NODE0 ~= NODE2 | NODE0 ~= NODE4 | NODE1 ~= NODE3 | NODE0 = NODE1) & (NODE0 ~= NODE2 | NODE1 ~= NODE3 | NODE1 = NODE4 | NODE0 = NODE1 | NODE0 = NODE4) & (NODE0 ~= NODE4 | NODE1 ~= NODE2 | NODE0 = NODE3 | NODE1 = NODE3 | NODE0 = NODE1) & (NODE1 ~= NODE4 | NODE1 ~= NODE2 | NODE0 = NODE3 | NODE1 = NODE3 | NODE0 = NODE1) & (NODE1 ~= NODE2 | NODE3 ~= NODE4 | NODE0 = NODE3 | NODE1 = NODE3 | NODE0 = NODE1) & (NODE1 ~= NODE2 | NODE1 = NODE3 | NODE0 = NODE1 | NODE1 = NODE4 | NODE0 = NODE3 | NODE3 = NODE4 | NODE0 = NODE4) & (NODE0 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE2 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 55
invariant [invar_5] forall NODE1,NODE0,NODE4,NODE3,NODE2. ~q(NODE1) | p(NODE3) | p(NODE4) | ~q(NODE0) | ~r(NODE2) | ((NODE0 ~= NODE3 | NODE1 ~= NODE4 | NODE1 ~= NODE2 | NODE0 = NODE1) & (NODE0 ~= NODE4 | NODE1 ~= NODE2 | NODE0 = NODE3 | NODE1 = NODE3 | NODE0 = NODE1) & (NODE1 ~= NODE4 | NODE1 ~= NODE2 | NODE0 = NODE3 | NODE1 = NODE3 | NODE0 = NODE1) & (NODE0 ~= NODE3 | NODE1 ~= NODE4 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE1 ~= NODE3 | NODE2 ~= NODE4 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE1 ~= NODE2 | NODE1 = NODE3 | NODE0 = NODE1 | NODE1 = NODE4 | NODE0 = NODE3 | NODE3 = NODE4 | NODE0 = NODE4) & (NODE2 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE0 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 55
invariant [invar_6] forall NODE1,NODE0,NODE4,NODE3,NODE2. ~q(NODE2) | ~q(NODE1) | p(NODE4) | ~r(NODE3) | ~q(NODE0) | ((NODE0 ~= NODE4 | NODE2 ~= NODE3 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE2 ~= NODE4 | NODE2 ~= NODE3 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE2 ~= NODE3 | NODE1 = NODE4 | NODE0 = NODE1 | NODE2 = NODE4 | NODE0 = NODE4 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE0 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE3 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 41
invariant [invar_7] forall NODE1,NODE0,NODE4,NODE3,NODE2. ~q(NODE2) | ~q(NODE1) | ~r(NODE4) | ~r(NODE3) | ~q(NODE0) | ((NODE1 ~= NODE3 | NODE2 ~= NODE4 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE2 ~= NODE3 | NODE1 = NODE4 | NODE0 = NODE1 | NODE2 = NODE4 | NODE0 = NODE4 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 22
invariant [invar_8] forall NODE1,NODE0,NODE4,NODE3,NODE2. p(NODE3) | p(NODE4) | ~r(NODE0) | ~r(NODE1) | ~r(NODE2) | ((NODE0 ~= NODE3 | NODE1 ~= NODE4 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE2 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 22
invariant [invar_9] forall NODE1,NODE0,NODE4,NODE3,NODE2. p(NODE4) | ~r(NODE3) | ~r(NODE1) | ~q(NODE0) | ~r(NODE2) | ((NODE0 ~= NODE1 | NODE0 ~= NODE4 | NODE0 = NODE3 | NODE0 = NODE2 | NODE2 = NODE3) & (NODE0 ~= NODE1 | NODE2 ~= NODE4 | NODE0 = NODE3 | NODE0 = NODE2 | NODE2 = NODE3) & (NODE0 ~= NODE1 | NODE2 = NODE4 | NODE2 = NODE3 | NODE0 = NODE3 | NODE3 = NODE4 | NODE0 = NODE4 | NODE0 = NODE2) & (NODE0 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE3 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 41
invariant [invar_10] forall NODE1,NODE0,NODE4,NODE3,NODE2. ~q(NODE1) | ~r(NODE4) | ~r(NODE3) | ~q(NODE0) | ~r(NODE2) | ((NODE0 ~= NODE2 | NODE1 ~= NODE4 | NODE0 = NODE3 | NODE1 = NODE3 | NODE0 = NODE1) & (NODE1 ~= NODE3 | NODE1 = NODE4 | NODE0 = NODE1 | NODE2 = NODE4 | NODE0 = NODE4 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 22
invariant [invar_11] forall NODE1. ~r(NODE1) | ~q(NODE1) | (exists NODE0. (~q(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_12] forall NODE1. ~r(NODE1) | ~q(NODE1) | (exists NODE0. (~r(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_13] forall NODE1. ~r(NODE1) | p(NODE1) | (exists NODE0. (~r(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_14] forall NODE1,NODE2,NODE3,NODE0. ~q(NODE2) | ~q(NODE1) | p(NODE3) | ~q(NODE0) | p(NODE0) | ((NODE1 ~= NODE3 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 19
invariant [invar_15] forall NODE1. p(NODE1) | ~q(NODE1) | (exists NODE0. (~q(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_16] forall NODE1,NODE2,NODE3,NODE0. ~q(NODE1) | p(NODE3) | p(NODE2) | ~q(NODE0) | p(NODE0) | ((NODE1 ~= NODE3 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 19
invariant [invar_17] forall NODE1. p(NODE1) | ~q(NODE1) | (exists NODE0. (p(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_18] forall NODE1,NODE0,NODE4,NODE3,NODE2. r(NODE2) | q(NODE0) | q(NODE4) | r(NODE0) | r(NODE1) | ~p(NODE3) | ~p(NODE1) | ~p(NODE0) | ~p(NODE2) | ((NODE3 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE2 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 28
invariant [invar_19] forall NODE7,NODE1,NODE0,NODE4,NODE3,NODE5,NODE6,NODE2. r(NODE7) | q(NODE4) | q(NODE3) | r(NODE6) | r(NODE3) | ~p(NODE1) | ~p(NODE0) | q(NODE5) | ~p(NODE2) | ((NODE0 ~= NODE3 | NODE1 ~= NODE6 | NODE1 ~= NODE4 | NODE2 ~= NODE7 | NODE2 ~= NODE5 | NODE0 = NODE2 | NODE0 = NODE1 | NODE1 = NODE2) & (NODE0 ~= NODE6 | NODE1 ~= NODE7 | NODE1 ~= NODE4 | NODE2 ~= NODE5 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE0 ~= NODE3 | NODE1 ~= NODE7 | NODE1 ~= NODE4 | NODE2 ~= NODE5 | NODE0 = NODE1 | NODE1 = NODE6 | NODE2 = NODE6 | NODE0 = NODE6 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE0 ~= NODE3 | NODE1 ~= NODE6 | NODE2 ~= NODE7 | NODE2 ~= NODE4 | NODE0 = NODE1 | NODE1 = NODE5 | NODE0 = NODE5 | NODE2 = NODE5 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE1 ~= NODE6 | NODE1 ~= NODE4 | NODE2 ~= NODE7 | NODE2 ~= NODE5 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 65
invariant [invar_20] forall NODE1,NODE0,NODE4,NODE3,NODE2. q(NODE2) | q(NODE0) | q(NODE3) | r(NODE0) | r(NODE4) | ~p(NODE3) | ~p(NODE1) | ~p(NODE0) | ~p(NODE2) | ((NODE2 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE1 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 28
invariant [invar_21] forall NODE1,NODE0,NODE4,NODE3,NODE2. q(NODE2) | r(NODE2) | q(NODE3) | r(NODE0) | r(NODE4) | r(NODE1) | ~p(NODE1) | ~p(NODE0) | ~p(NODE2) | ((NODE3 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE1 ~= NODE3 | NODE1 = NODE4 | NODE0 = NODE1 | NODE2 = NODE4 | NODE0 = NODE4 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 28
invariant [invar_22] forall NODE1,NODE0,NODE4,NODE3,NODE5,NODE2. r(NODE5) | q(NODE2) | r(NODE2) | q(NODE4) | q(NODE3) | r(NODE3) | r(NODE4) | ~p(NODE1) | ~p(NODE0) | ((NODE0 ~= NODE5 | NODE1 ~= NODE3 | NODE1 = NODE4 | NODE0 = NODE1 | NODE2 = NODE4 | NODE0 = NODE4 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE0 ~= NODE3 | NODE1 ~= NODE4 | NODE0 = NODE1 | NODE1 = NODE5 | NODE0 = NODE5 | NODE2 = NODE5 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 31
invariant [invar_23] forall NODE1. q(NODE1) | r(NODE1) | ~p(NODE1) | (exists NODE0. ((r(NODE0) | ~p(NODE0)) & NODE0 ~= NODE1)) # qcost: 8
invariant [invar_24] forall NODE1,NODE0,NODE4,NODE3,NODE2. q(NODE2) | r(NODE2) | q(NODE0) | q(NODE3) | q(NODE4) | r(NODE0) | r(NODE3) | ~p(NODE1) | ~p(NODE0) | ((NODE1 ~= NODE2 | NODE1 = NODE3 | NODE0 = NODE1 | NODE1 = NODE4 | NODE0 = NODE3 | NODE3 = NODE4 | NODE0 = NODE4) & (NODE1 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 28
invariant [invar_25] forall NODE1,NODE0,NODE4,NODE3,NODE2. q(NODE2) | q(NODE0) | q(NODE1) | q(NODE3) | r(NODE0) | r(NODE4) | ~p(NODE1) | ~p(NODE0) | ~p(NODE2) | ((NODE3 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2) & (NODE1 ~= NODE4 | NODE1 = NODE3 | NODE0 = NODE1 | NODE2 = NODE3 | NODE0 = NODE3 | NODE1 = NODE2 | NODE0 = NODE2)) # qcost: 28
invariant [invar_26] forall NODE1. q(NODE1) | r(NODE1) | ~p(NODE1) | (exists NODE0. ((q(NODE0) | ~p(NODE0)) & NODE0 ~= NODE1)) # qcost: 8
invariant [invar_27] forall NODE1. q(NODE1) | r(NODE1) | ~p(NODE1) | (exists NODE0. ((q(NODE0) | r(NODE0)) & NODE0 ~= NODE1)) # qcost: 8

### For QRM DFS reachability ###

## Dependent relation axioms ##

## Access actions ##
action get_r(n0: node) returns(qrm_result: bool) = {
    qrm_result := r(n0)
}
export get_r

action get_bool_r(n0: node, result: bool) returns(qrm_result: bool) = {
    qrm_result := (r(n0) = result)
}
export get_bool_r

action get_p(n0: node) returns(qrm_result: bool) = {
    qrm_result := p(n0)
}
export get_p

action get_bool_p(n0: node, result: bool) returns(qrm_result: bool) = {
    qrm_result := (p(n0) = result)
}
export get_bool_p

action get_q(n0: node) returns(qrm_result: bool) = {
    qrm_result := q(n0)
}
export get_q

action get_bool_q(n0: node, result: bool) returns(qrm_result: bool) = {
    qrm_result := (q(n0) = result)
}
export get_bool_q

