#lang ivy1.8

type node

relation p(X:node)
relation q(X:node)
relation r(X:node)

after init {
    p(X) := false;
    q(X) := false;
    r(X) := false;
}

action upq(x:node,y:node) = {
    require ~p(x) & ~q(y);
    p(x) := true;
    q(y) := true;
}

action upr(x:node,y:node) = {
    require ~p(x) & ~r(y);
    p(x) := true;
    r(y) := true;
}

action downq(x:node,y:node) = {
    require p(x) & q(y);
    p(x) := false;
    q(y) := false;
}

action downr(x:node,y:node) = {
    require p(x) & r(y);
    p(x) := false;
    r(y) := false;
}

#invariant p(X) -> exists Y. (q(Y) | r(Y))

export upq
export upr
export downq
export downr


invariant [invar_0] forall NODE2,NODE1,NODE3,NODE0. ~r(NODE2) | ~q(NODE1) | p(NODE3) | ~q(NODE0) | ((NODE0 = NODE1 & NODE0 = NODE2 & NODE0 ~= NODE3) | (NODE0 = NODE1 & NODE2 = NODE3 & NODE0 ~= NODE2) | (NODE0 = NODE1 & NODE0 = NODE3 & NODE0 ~= NODE2) | (NODE0 = NODE1 & NODE0 = NODE3 & NODE0 = NODE2) | (NODE0 = NODE1 & NODE0 ~= NODE2 & NODE2 ~= NODE3 & NODE0 ~= NODE3)) # qcost: 24
invariant [invar_1] forall NODE2,NODE1,NODE0. ~r(NODE2) | ~r(NODE0) | ~q(NODE1) | ~q(NODE0) | (NODE0 = NODE1 & NODE0 ~= NODE2) # qcost: 9
invariant [invar_2] forall NODE2,NODE1,NODE3,NODE0. ~r(NODE2) | ~r(NODE1) | p(NODE3) | ~q(NODE0) | ((NODE0 = NODE1 & NODE0 = NODE2 & NODE0 ~= NODE3) | (NODE1 = NODE2 & NODE1 = NODE3 & NODE0 ~= NODE1) | (NODE0 = NODE3 & NODE1 = NODE2 & NODE0 ~= NODE1) | (NODE0 = NODE1 & NODE0 = NODE3 & NODE0 = NODE2) | (NODE1 = NODE2 & NODE1 ~= NODE3 & NODE0 ~= NODE3 & NODE0 ~= NODE1)) # qcost: 24
invariant [invar_3] forall NODE2,NODE1,NODE3,NODE0. ~q(NODE0) | ~r(NODE1) | p(NODE3) | p(NODE2) | ((NODE0 = NODE1 & NODE2 = NODE3 & NODE0 ~= NODE2) | (NODE1 = NODE2 & NODE1 = NODE3 & NODE0 ~= NODE1) | (NODE0 = NODE3 & NODE0 = NODE2 & NODE0 ~= NODE1) | (NODE0 = NODE1 & NODE0 = NODE3 & NODE0 = NODE2) | (NODE2 = NODE3 & NODE0 ~= NODE2 & NODE1 ~= NODE2 & NODE0 ~= NODE1)) # qcost: 24
invariant [invar_4] forall NODE2,NODE1,NODE3,NODE0. ~q(NODE0) | ~q(NODE1) | p(NODE3) | p(NODE2) | ((NODE0 ~= NODE2 | NODE1 ~= NODE3 | NODE0 = NODE1) & (NODE1 ~= NODE2 | NODE1 = NODE3 | NODE0 = NODE3 | NODE0 = NODE1)) # qcost: 15
invariant [invar_5] forall NODE1. ~q(NODE1) | p(NODE1) | (exists NODE0. (p(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_6] forall NODE1. ~r(NODE1) | ~q(NODE1) | (exists NODE0. (~r(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_7] forall NODE2,NODE1,NODE3,NODE0. ~r(NODE1) | ~r(NODE0) | p(NODE3) | p(NODE2) | ((NODE0 ~= NODE2 | NODE1 ~= NODE3 | NODE0 = NODE1) & (NODE1 ~= NODE2 | NODE1 = NODE3 | NODE0 = NODE3 | NODE0 = NODE1)) # qcost: 15
invariant [invar_8] forall NODE1. ~r(NODE1) | p(NODE1) | (exists NODE0. (~r(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_9] forall NODE1. ~r(NODE1) | p(NODE1) | (exists NODE0. (p(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_10] forall NODE1. ~r(NODE1) | ~q(NODE1) | (exists NODE0. (~q(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_11] forall NODE1. ~q(NODE1) | p(NODE1) | (exists NODE0. (~q(NODE0) & NODE0 ~= NODE1)) # qcost: 6
invariant [invar_12] forall NODE2,NODE1,NODE3,NODE0. q(NODE0) | r(NODE0) | r(NODE3) | ~p(NODE0) | ~p(NODE1) | ~p(NODE2) | q(NODE1) | ((NODE1 ~= NODE3 | NODE0 = NODE2 | NODE1 = NODE2 | NODE0 = NODE1) & (NODE2 ~= NODE3 | NODE0 = NODE2 | NODE1 = NODE2 | NODE0 = NODE1)) # qcost: 19
invariant [invar_13] forall NODE1. ~p(NODE1) | q(NODE1) | r(NODE1) | (exists NODE0. ((r(NODE0) | ~p(NODE0)) & NODE0 ~= NODE1)) # qcost: 8
invariant [invar_14] forall NODE2,NODE1,NODE3,NODE0. q(NODE0) | r(NODE0) | r(NODE3) | ~p(NODE0) | ~p(NODE1) | q(NODE2) | r(NODE2) | ((NODE1 ~= NODE3 | NODE0 = NODE2 | NODE1 = NODE2 | NODE0 = NODE1) & (NODE1 ~= NODE2 | NODE1 = NODE3 | NODE0 = NODE3 | NODE0 = NODE1)) # qcost: 19
invariant [invar_15] forall NODE1. ~p(NODE1) | q(NODE1) | r(NODE1) | (exists NODE0. ((q(NODE0) | r(NODE0)) & NODE0 ~= NODE1)) # qcost: 8
invariant [invar_16] forall NODE2,NODE1,NODE3,NODE0. q(NODE0) | r(NODE0) | r(NODE3) | ~p(NODE0) | ~p(NODE1) | q(NODE2) | q(NODE1) | ((NODE2 ~= NODE3 | NODE0 = NODE2 | NODE1 = NODE2 | NODE0 = NODE1) & (NODE1 ~= NODE3 | NODE0 = NODE2 | NODE1 = NODE2 | NODE0 = NODE1)) # qcost: 19
invariant [invar_17] forall NODE1. ~p(NODE1) | q(NODE1) | r(NODE1) | (exists NODE0. ((q(NODE0) | ~p(NODE0)) & NODE0 ~= NODE1)) # qcost: 8
