#lang ivy1.8

type node

relation p(X:node)
relation q(X:node)
relation r(X:node)

# Does this p-node pair with q (true) or r (false)?
relation use_q(X:node)

# p <-> q pairing
function pq(X:node) : node
function qp(X:node) : node

# p <-> r pairing
function pr(X:node) : node
function rp(X:node) : node

after init {
    p(X) := false;
    q(X) := false;
    r(X) := false;
    use_q(X) := false;
    pq(X) := X;
    pr(X) := X;
    qp(X) := X;
    rp(X) := X;   
}

action upq(x:node,y:node) = {
    require ~p(x) & ~q(y);
    p(x) := true;
    q(y) := true;
    use_q(x) := true;
    pq(x) := y;
    qp(y) := x;
}

action upr(x:node,y:node) = {
    require ~p(x) & ~r(y);
    p(x) := true;
    r(y) := true;
    use_q(x) := false;
    pr(x) := y;
    rp(y) := x;
}

# Remove one p and one q.
action downq(x:node,y:node) = {
    require p(x) & q(y);
    if use_q(x) {
        pq(qp(y)) := pq(x);
        qp(pq(x)) := qp(y);
        # use_q(qp(y)) stays true
    } else {
        pr(qp(y)) := pr(x);
        rp(pr(x)) := qp(y);
        use_q(qp(y)) := false;
    };
    p(x) := false;
    q(y) := false;
    pq(x) := x;
    pr(x) := x;
    qp(y) := y;
}

# Remove one p and one r.
action downr(x:node,y:node) = {
    require p(x) & r(y);
    if ~use_q(x) {
        pr(rp(y)) := pr(x);
        rp(pr(x)) := rp(y);
        # use_q(rp(y)) stays false
    } else {
        pq(rp(y)) := pq(x);
        qp(pq(x)) := rp(y);
        use_q(rp(y)) := true;
    };
    p(x) := false;
    r(y) := false;
    pq(x) := x;
    pr(x) := x;
    qp(y) := y;
}

# invariant p(X) -> exists Y. (q(Y) | r(Y))


export upq
export upr
export downq
export downr
