#lang ivy1.8

type node

relation p(X:node)
relation q(X:node)
relation r(X:node)

after init {
    p(X) := false;
    q(X) := false;
    r(X) := false;
}

action upq(x:node,y:node) = {
    require ~p(x) & ~q(y);
    p(x) := true;
    q(y) := true;
}

action upr(x:node,y:node) = {
    require ~p(x) & ~r(y);
    p(x) := true;
    r(y) := true;
}

action downq(x:node,y:node) = {
    require p(x) & q(y);
    p(x) := false;
    q(y) := false;
}

action downr(x:node,y:node) = {
    require p(x) & r(y);
    p(x) := false;
    r(y) := false;
}

invariant p(X) -> exists Y. (q(Y) | r(Y))

export upq
export upr
export downq
export downr

