sym_path='ivybench/sym/ivy/'
sym_quorum_path='ivybench/sym_quorum/ivy/'
sym_ring_path='ivybench/sym_ring/ivy/'
yaml_path='yamls/'
Timeout=2000 #second
Memout=15000 #15GB

./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}Consensus.ivy                            -s value=4                         -v 5 -w -l ${sym_path}Consensus.bdd.log                            2> ${sym_path}Consensus.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}TCommit.ivy                              -s resource_manager=3              -v 5 -w -l ${sym_path}TCommit.bdd.log                              2> ${sym_path}TCommit.bdd.runlim.log                                            
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}Ricart-Agrawala.ivy                      -s node=3                          -v 5 -w -l ${sym_path}Ricart-Agrawala.bdd.log                      2> ${sym_path}Ricart-Agrawala.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}lock_server.ivy                          -s server=2,client=4               -v 5 -w -l ${sym_path}lock_server.bdd.log                          2> ${sym_path}lock_server.bdd.runlim.log                                     
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}sharded_kv.ivy                           -s node=4,key=2,value=3            -v 5 -w -l ${sym_path}sharded_kv.bdd.log                           2> ${sym_path}sharded_kv.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}sharded_kv_no_lost_keys.ivy              -s node=4,key=2,value=3            -v 5 -w -l ${sym_path}sharded_kv_no_lost_keys.bdd.log              2> ${sym_path}sharded_kv_no_lost_keys.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}simple-decentralized-lock.ivy            -s node=4                          -v 5 -w -l ${sym_path}simple-decentralized-lock.bdd.log            2> ${sym_path}simple-decentralized-lock.bdd.runlim.log 
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}firewall.ivy                             -s node=4                          -v 5 -w -l ${sym_path}firewall.bdd.log                             2> ${sym_path}firewall.bdd.runlim.log 
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}lockserv.ivy                             -s node=4                          -v 5 -w -l ${sym_path}lockserv.bdd.log                             2> ${sym_path}lockserv.bdd.runlim.log 
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}lockserv_automaton.ivy                   -s node=4                          -v 5 -w -l ${sym_path}lockserv_automaton.bdd.log                   2> ${sym_path}lockserv_automaton.bdd.runlim.log 
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}TwoPhase.ivy                             -s resource_manager=2              -v 5 -w -l ${sym_path}TwoPhase.bdd.log                             2> ${sym_path}TwoPhase.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_path}client_server_ae.ivy                     -s node=2,request=2,response=2     -v 5 -w -l ${sym_path}client_server_ae.bdd.log                     2> ${sym_path}client_server_ae.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_quorum_path}naive_consensus.ivy               -s node=4,quorum=4,value=4         -v 5 -w -l ${sym_quorum_path}naive_consensus.bdd.log               2> ${sym_path}naive_consensus.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_quorum_path}toy_consensus.ivy                 -s node=4,quorum=4,value=4         -v 5 -w -l ${sym_quorum_path}toy_consensus.bdd.log                 2> ${sym_path}toy_consensus.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_quorum_path}toy_consensus_epr.ivy             -s node=4,quorum=4,value=4         -v 5 -w -l ${sym_quorum_path}toy_consensus_epr.bdd.log             2> ${sym_path}toy_consensus_epr.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_quorum_path}simple-election.ivy               -s acceptor=4,quorum=4,proposer=4  -v 5 -w -l ${sym_quorum_path}simple-election.bdd.log               2> ${sym_path}simple-election.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_quorum_path}consensus_epr.ivy                 -s node=4,quorum=4,value=3         -v 5 -w -l ${sym_quorum_path}consensus_epr.bdd.log                 2> ${sym_path}consensus_epr.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_quorum_path}toy_consensus_forall.ivy          -s node=4,quorum=4,value=4         -v 5 -w -l ${sym_quorum_path}toy_consensus_forall.bdd.log          2> ${sym_path}toy_consensus_forall.bdd.runlim.log
./runlim --time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py -i ${sym_quorum_path}quorum-leader-election-wo-maj.ivy -s node=6,nset=15                  -v 5 -w -l ${sym_quorum_path}quorum-leader-election-wo-maj.bdd.log 2> ${sym_path}quorum-leader-election-wo-maj.bdd.runlim.log
