sym_path='ivybench/sym/ivy/'
sym_quorum_path='ivybench/sym_quorum/ivy/'
sym_ring_path='ivybench/sym_ring/ivy/'
yaml_path='yamls/'
Timeout=2000 #second
Memout=15000 #15GB

./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}Consensus.ivy                            -s value=4                             -v 5 -w -l ${sym_path}Consensus.fw.log                            2> ${sym_path}Consensus.fw.runlim.log
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}TCommit.ivy                              -s resource_manager=3                  -v 5 -w -l ${sym_path}TCommit.fw.log                              2> ${sym_path}TCommit.fw.runlim.log                                                                    
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}Ricart-Agrawala.ivy                      -s node=3                              -v 5 -w -l ${sym_path}Ricart-Agrawala.fw.log                      2> ${sym_path}Ricart-Agrawala.fw.runlim.log                                                        
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}lock_server.ivy                          -s server=2,client=4                   -v 5 -w -l ${sym_path}lock_server.fw.log                          2> ${sym_path}lock_server.fw.runlim.log                                                                                              
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}sharded_kv.ivy                           -s node=4,key=2,value=3                -v 5 -w -l ${sym_path}sharded_kv.fw.log                           2> ${sym_path}sharded_kv.fw.runlim.log                                                             
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}sharded_kv_no_lost_keys.ivy              -s node=4,key=2,value=3                -v 5 -w -l ${sym_path}sharded_kv_no_lost_keys.fw.log              2> ${sym_path}sharded_kv_no_lost_keys.fw.runlim.log                                                
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}simple-decentralized-lock.ivy            -s node=4                              -v 5 -w -l ${sym_path}simple-decentralized-lock.fw.log            2> ${sym_path}simple-decentralized-lock.fw.runlim.log                                                  
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}firewall.ivy                             -s node=4                              -v 5 -w -l ${sym_path}firewal.fw.log                              2> ${sym_path}firewall.fw.runlim.log                                                                   
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}lockserv.ivy                             -s node=4                              -v 5 -w -l ${sym_path}lockserv.fw.log                             2> ${sym_path}lockserv.fw.runlim.log                                                                   
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}lockserv_automaton.ivy                   -s node=4                              -v 5 -w -l ${sym_path}lockserv_automaton.fw.log                   2> ${sym_path}lockserv_automaton.fw.runlim.log                                                             
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}client_server_ae.ivy                     -s node=2,request=2,response=2         -v 5 -w -l ${sym_path}client_server_ae.fw.log                     2> ${sym_path}client_server_ae.fw.runlim.log                                                                           
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_path}TwoPhase.ivy                             -s resource_manager=2                  -v 5 -w -l ${sym_path}TwoPhase.fw.log                             2> ${sym_path}TwoPhase.fw.runlim.log
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_quorum_path}toy_consensus.ivy                 -s node=4,value=4                      -v 5 -w -l ${sym_quorum_path}toy_consensus.fw.log                 2> ${sym_quorum_path}toy_consensus.fw.runlim.log                                                                   
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_quorum_path}toy_consensus_epr.ivy             -s node=4,value=4                      -v 5 -w -l ${sym_quorum_path}toy_consensus_epr.fw.log             2> ${sym_quorum_path}toy_consensus_epr.fw.runlim.log                                                                 
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_quorum_path}naive_consensus.ivy               -s node=4,value=4                      -v 5 -w -l ${sym_quorum_path}naive_consensus.fw.log               2> ${sym_quorum_path}naive_consensus.fw.runlim.log                                                             
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_quorum_path}simple-election.ivy               -s acceptor=4,proposer=4               -v 5 -w -l ${sym_quorum_path}simple-election.fw.log               2> ${sym_quorum_path}simple-election.fw.runlim.log                                                                    
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_quorum_path}toy_consensus_forall.ivy          -s node=4,value=4                      -v 5 -w -l ${sym_quorum_path}toy_consensus_forall.fw.log          2> ${sym_quorum_path}toy_consensus_forall.fw.runlim.log
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_quorum_path}quorum-leader-election-wo-maj.ivy -s node=6                              -v 5 -w -l ${sym_quorum_path}quorum-leader-election-wo-maj.fw.log 2> ${sym_quorum_path}quorum-leader-election-wo-maj.fw.runlim.log                                                                        
./runlim --time-limit=${Timeout} --real-time-limit=${Timeout} --space-limit=${Memout} python3 qrm.py ${sym_quorum_path}consensus_epr.ivy                 -s node=4,value=3                      -v 5 -w -l ${sym_quorum_path}consensus_epr.fw.log                 2> ${sym_quorum_path}consensus_epr.fw.runlim.log                  