#lang ivy1.7

#
# An Ivy model of the toy lock example from https://github.com/Microsoft/Ironclad/blob/master/ironfleet/src/Dafny/Distributed/Protocol/Lock/Node.i.dfy
#
# For a description of the protocol, see the IronFleet paper
# (https://www.microsoft.com/en-us/research/wp-content/uploads/2015/10/ironfleet.pdf),
# Figure 4
#

# A total order helper module
module total_order(r) = {
    axiom r(X,X)                        # Reflexivity
    axiom r(X, Y) & r(Y, Z) -> r(X, Z)  # Transitivity
    axiom r(X, Y) & r(Y, X) -> X = Y    # Anti-symmetry
    axiom r(X, Y) | r(Y, X)             # Totality
}

################################################################################
#
# Types, relations and functions describing state of the network
#
################################################################################

type node
type epoch

# epochs are totally ordered with a least element called zero
relation le(X:epoch, Y:epoch)
instantiate total_order(le)
individual zero:epoch
axiom le(zero, X)
individual max:epoch
axiom le(X, max)

function ep(N:node) : epoch # ep(n) is the current epoch of node n

relation held(N:node) # held(n) is true iff the lock is currently held by node n

# transfer messages
relation transfer(E:epoch, N:node)  # the node is the message destination

# locked messages
relation locked(E:epoch, N:node)  # the node is the message source

################################################################################
#
# Protocol description
#
################################################################################
individual first:node
individual firste:epoch
axiom firste ~= zero

after init {
    # initially exactly one node holds the lock, and everyone has epoch zero
    held(X) := X=first;
    ep(N) := firste if N = first else zero;
    transfer(E, N) := false;
    locked(E, N) := false;
}

action grant(n1:node, n2:node, e:epoch) = {
    # release the lock and send a transfer message
    require held(n1);
    require ~le(e, ep(n1));   # e must be strictly higher than current epoch
    # no epoch can lie strictly between ep(n1) and e (i.e., e is next-higher)
    require (forall E2:epoch . le(ep(n1), E2) & le(E2, e) -> E2 = ep(n1) | E2 = e);
    transfer(e, n2) := true;
    held(n1) := false;
}

action accept(n:node, e:epoch) = {
    # receive a transfer message and take the lock, sending a locked message
    require transfer(e,n);
    require ~le(e,ep(n));
    transfer(e,n) := false;
    held(n) := true;
    ep(n) := e;
    locked(e, n) := true;

}

export grant
export accept

# the safety property
## invariant locked(E, N1) & locked(E, N2) -> N1 = N2

# epochs transfer to at most one node    
##invariant [manual_1] transfer(E, N1) & transfer(E, N2) -> N1 = N2

# if a node sent a locked msg, the node's epoch is now higher
##invariant [manual_2] locked(E, N) -> le(E, ep(N))

# holding node's epoch is higher than any other node's epoch (this implies a single node holds the lock)
##invariant [manual_3] held(N) & N ~= M -> ~le(ep(N), ep(M))

# holding node's epoch is higher than any transfer's epoch
##invariant [manual_4] held(N) & transfer(E, M) -> le(E, ep(N))

# pending transfer epoch is higher than any node's epoch
##invariant [manual_5] transfer(E, N) & ~le(E, ep(N)) -> ~le(E, ep(M))

# pending transfer epoch is higher than any transfer's epoch
##invariant [manual_6] transfer(E, N) & ~le(E, ep(N)) & transfer(F, M) -> le(F, E) 

# python3 qrm.py ivybench/total/ivy/distributed_lock.ivy -s node=3,epoch=4 -f 2 -w -g -r -v 5 -l test.log -y

## invariant [invar_5] forall NODE0. ~locked(zero, NODE0)
## invariant [invar_1] forall NODE0. ~transfer(firste, NODE0)
## invariant [invar_2] forall E. exists NODE0. ~le(E, firste) -> ~transfer(E, NODE0)
## invariant [invar_14] forall E, NODE0, NODE1. ~le(E, firste) -> ~held(NODE0) | ~transfer(E, NODE1)
## invariant [invar_6] forall E0, E1, NODE0, NODE1. ~le(E0, firste) & le(E0, E1) -> ~locked(E1, NODE0) | ~transfer(E0, NODE1)
## invariant [invar_7] forall E. exists NODE0. ~le(E, zero) -> ~locked(E, NODE0)
## invariant [invar_122] forall E0, E1, NODE0, NODE1. le(E0, E1) -> ep(NODE0) ~= E1 | ~transfer(E0, NODE1)
## invariant [invar_123] forall E, NODE0. ~le(E, zero) -> ep(NODE0) ~= E | locked(E, NODE0)
## invariant [invar_126] forall E, NODE0, NODE1. ~le(E, zero) -> ~locked(E, NODE1) | ep(NODE0) ~= E | NODE0 = NODE1
## invariant [invar_160] forall E. exists NODE0. ep(NODE0) ~= E
## invariant [invar_125] forall E0, E1, NODE0. le(E0, E1) -> ~locked(E1, NODE0) | ep(NODE0) ~= E0
## invariant [invar_159] forall E0, E1, NODE0. (E0 ~= E1) -> ep(NODE0) ~= E0 | ep(NODE0) ~= E1
## invariant [invar_200] forall NODE0. ~locked(zero, NODE0)
## invariant [invar_201] forall NODE0. ~transfer(firste, NODE0)
## invariant [invar_202] forall NODE0. ep(NODE0) ~= zero | ~held(NODE0)
## invariant [invar_203] forall NODE0,NODE1. locked(firste, NODE1) | ep(NODE0) ~= zero | NODE0 = NODE1
## invariant [invar_204] forall NODE0,NODE1. ep(NODE0) ~= max | ~held(NODE1) | NODE0 = NODE1
## invariant [invar_205] forall NODE0. held(NODE0) | ep(NODE0) ~= max
## invariant [invar_206] exists NODE0. ~held(NODE0)
## invariant [invar_207] forall NODE0,NODE1. ~held(NODE0) | ~locked(max, NODE1) | NODE0 = NODE1
## invariant [invar_208] forall NODE0. ep(NODE0) = max | ~locked(max, NODE0)
## invariant [invar_209] forall NODE0. held(NODE0) | ~locked(max, NODE0)
## invariant [invar_210] forall E0,E1,NODE0,NODE1. le(firste, E0) & le(E0, E1) & E0 ~= E1 -> ~transfer(E1, NODE1) | ~transfer(E0, NODE0)
## invariant [invar_211] exists NODE0. locked(firste, NODE0)
invariant [invar_0] forall NODE0. ~locked_epoch0(NODE0) # qcost: 2
invariant [invar_1] forall NODE0. ~locked_epoch1(NODE0) # qcost: 2
invariant [invar_2] forall NODE0. ~transfer_epoch0(NODE0) # qcost: 2
invariant [invar_3] forall NODE0. ~transfer_epoch1(NODE0) # qcost: 2
invariant [invar_1027] exists NODE0. ep_epoch0(NODE0) | ep_epoch1(NODE0) | locked_epoch3(NODE0) # qcost: 4
invariant [invar_1028] exists NODE0. ep_epoch0(NODE0) | ep_epoch2(NODE0) | locked_epoch3(NODE0) # qcost: 4
invariant [invar_1409] exists NODE0. ep_epoch1(NODE0) | ep_epoch2(NODE0) | ep_epoch3(NODE0) | locked_epoch4(NODE0) # qcost: 5
invariant [invar_10] forall NODE0. ~ep_epoch0(NODE0) | ~held(NODE0) # qcost: 3
invariant [invar_11] forall NODE0. ~ep_epoch0(NODE0) | ~locked_epoch2(NODE0) # qcost: 3
invariant [invar_12] forall NODE0. ~ep_epoch0(NODE0) | ~locked_epoch3(NODE0) # qcost: 3
invariant [invar_13] forall NODE0. ~ep_epoch0(NODE0) | ~locked_epoch4(NODE0) # qcost: 3
invariant [invar_14] forall NODE0. ~ep_epoch0(NODE0) | ~locked_epoch5(NODE0) # qcost: 3
invariant [invar_20] forall NODE0. ~ep_epoch1(NODE0) | ~locked_epoch2(NODE0) # qcost: 3
invariant [invar_21] forall NODE0. ~ep_epoch1(NODE0) | ~locked_epoch3(NODE0) # qcost: 3
invariant [invar_22] forall NODE0. ~ep_epoch1(NODE0) | ~locked_epoch4(NODE0) # qcost: 3
invariant [invar_23] forall NODE0. ~ep_epoch1(NODE0) | ~locked_epoch5(NODE0) # qcost: 3
invariant [invar_29] forall NODE0. ~ep_epoch2(NODE0) | ~locked_epoch3(NODE0) # qcost: 3
invariant [invar_30] forall NODE0. ~ep_epoch2(NODE0) | ~locked_epoch4(NODE0) # qcost: 3
invariant [invar_31] forall NODE0. ~ep_epoch2(NODE0) | ~locked_epoch5(NODE0) # qcost: 3
invariant [invar_38] forall NODE0. ~ep_epoch3(NODE0) | ~locked_epoch4(NODE0) # qcost: 3
invariant [invar_39] forall NODE0. ~ep_epoch3(NODE0) | ~locked_epoch5(NODE0) # qcost: 3
invariant [invar_1064] exists NODE0. ep_epoch1(NODE0) | ep_epoch2(NODE0) | locked_epoch3(NODE0) # qcost: 4
invariant [invar_46] forall NODE0. ~ep_epoch4(NODE0) | ~locked_epoch5(NODE0) # qcost: 3
invariant [invar_1328] exists NODE0. ep_epoch0(NODE0) | ep_epoch1(NODE0) | ep_epoch2(NODE0) | locked_epoch4(NODE0) # qcost: 5
invariant [invar_1329] exists NODE0. ep_epoch0(NODE0) | ep_epoch1(NODE0) | ep_epoch3(NODE0) | locked_epoch4(NODE0) # qcost: 5
invariant [invar_310] exists NODE0. ep_epoch0(NODE0) | locked_epoch2(NODE0) # qcost: 3
invariant [invar_312] exists NODE0. ep_epoch1(NODE0) | locked_epoch2(NODE0) # qcost: 3
invariant [invar_1338] exists NODE0. ep_epoch0(NODE0) | ep_epoch2(NODE0) | ep_epoch3(NODE0) | locked_epoch4(NODE0) # qcost: 5
invariant [invar_1851] exists NODE0. held(NODE0) | transfer_epoch2(NODE0) | transfer_epoch3(NODE0) | transfer_epoch4(NODE0) | transfer_epoch5(NODE0) # qcost: 6
invariant [invar_60] exists NODE0. ~held(NODE0) # qcost: 2
invariant [invar_62] forall NODE1,NODE0. ~held(NODE0) | ~transfer_epoch2(NODE1) # qcost: 4
invariant [invar_63] forall NODE1,NODE0. ~held(NODE0) | ~transfer_epoch3(NODE1) # qcost: 4
invariant [invar_64] forall NODE1,NODE0. ~held(NODE0) | ~transfer_epoch4(NODE1) # qcost: 4
invariant [invar_65] forall NODE1,NODE0. ~held(NODE0) | ~transfer_epoch5(NODE1) # qcost: 4
invariant [invar_66] exists NODE0. ~locked_epoch2(NODE0) # qcost: 2
invariant [invar_68] exists NODE0. ~locked_epoch3(NODE0) # qcost: 2
invariant [invar_71] exists NODE0. ~locked_epoch4(NODE0) # qcost: 2
invariant [invar_75] exists NODE0. ~locked_epoch5(NODE0) # qcost: 2
invariant [invar_82] exists NODE0. ~transfer_epoch2(NODE0) # qcost: 2
invariant [invar_83] forall NODE1,NODE0. ~transfer_epoch2(NODE0) | ~transfer_epoch3(NODE1) # qcost: 4
invariant [invar_84] forall NODE1,NODE0. ~transfer_epoch2(NODE0) | ~transfer_epoch4(NODE1) # qcost: 4
invariant [invar_85] forall NODE1,NODE0. ~transfer_epoch2(NODE0) | ~transfer_epoch5(NODE1) # qcost: 4
invariant [invar_86] exists NODE0. ~transfer_epoch3(NODE0) # qcost: 2
invariant [invar_87] forall NODE1,NODE0. ~transfer_epoch3(NODE0) | ~transfer_epoch4(NODE1) # qcost: 4
invariant [invar_88] forall NODE1,NODE0. ~transfer_epoch3(NODE0) | ~transfer_epoch5(NODE1) # qcost: 4
invariant [invar_89] exists NODE0. ~transfer_epoch4(NODE0) # qcost: 2
invariant [invar_90] forall NODE1,NODE0. ~transfer_epoch4(NODE0) | ~transfer_epoch5(NODE1) # qcost: 4
invariant [invar_91] exists NODE0. ~transfer_epoch5(NODE0) # qcost: 2
invariant [invar_81] forall NODE0. ~locked_epoch5(NODE0) | held(NODE0) # qcost: 3
invariant [invar_33] forall NODE0. ~ep_epoch2(NODE0) | locked_epoch2(NODE0) # qcost: 3
invariant [invar_42] forall NODE0. ~ep_epoch3(NODE0) | locked_epoch3(NODE0) # qcost: 3
invariant [invar_50] forall NODE0. ~ep_epoch4(NODE0) | locked_epoch4(NODE0) # qcost: 3
invariant [invar_59] forall NODE0. ~ep_epoch5(NODE0) | locked_epoch5(NODE0) # qcost: 3
invariant [invar_67] forall NODE1,NODE0. ~locked_epoch2(NODE0) | ~transfer_epoch2(NODE1) # qcost: 4
invariant [invar_69] forall NODE1,NODE0. ~locked_epoch3(NODE0) | ~transfer_epoch2(NODE1) # qcost: 4
invariant [invar_70] forall NODE1,NODE0. ~locked_epoch3(NODE0) | ~transfer_epoch3(NODE1) # qcost: 4
invariant [invar_72] forall NODE1,NODE0. ~locked_epoch4(NODE0) | ~transfer_epoch2(NODE1) # qcost: 4
invariant [invar_73] forall NODE1,NODE0. ~locked_epoch4(NODE0) | ~transfer_epoch3(NODE1) # qcost: 4
invariant [invar_74] forall NODE1,NODE0. ~locked_epoch4(NODE0) | ~transfer_epoch4(NODE1) # qcost: 4
invariant [invar_76] forall NODE1,NODE0. ~locked_epoch5(NODE0) | ~transfer_epoch2(NODE1) # qcost: 4
invariant [invar_77] forall NODE1,NODE0. ~locked_epoch5(NODE0) | ~transfer_epoch3(NODE1) # qcost: 4
invariant [invar_78] forall NODE1,NODE0. ~locked_epoch5(NODE0) | ~transfer_epoch4(NODE1) # qcost: 4
invariant [invar_79] forall NODE1,NODE0. ~locked_epoch5(NODE0) | ~transfer_epoch5(NODE1) # qcost: 4
